import './globals.css'
import { Inter } from 'next/font/google'

// Initialize Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] })

/**
 * Application metadata configuration
 * Defines core SEO properties for the application
 */
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * Root layout component that wraps all pages
 * Provides common structure and styling across the application
 * @param {Object} props - Component properties
 * @param {React.ReactNode} props.children - Child components to be rendered within the layout
 * @returns {JSX.Element} The rendered layout structure
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
